Shopping cart
Ariiiane/InGame-Emporium-soen341project2022 pull request #44
Opened 2022-03-18 00:42 UTC by Ariiiane

![image](https://user-images.githubusercontent.com/53889883/158915977-a9fb981c-e4bf-406d-8947-c73ce8643e68.png)

Front end is finish, and functionality (back end) is to be implemented in the next task

2022-03-18 18:00 UTC, AryanSh1380 reviewed
After pulling ShoppingCart branch, the footer is now in the middle of the page and doesn't appear at the bottom. Moreover, when pressing on add to cart, nothing happens. Cart tab is also no redirecting anywhere

2022-03-19 16:52 UTC, JR-prog requested changes
Please add a link to /cart (from the header).
Also, the footer is also locked for me, and I cannot see most of the information in most pages. It also seems like some of the css is inconsistent (proceed to checkout button hard to read).

2022-03-20 13:10 UTC, Ariiiane commented
Task: #19: Implement cart page layout

The cart link has been added, can you please provide a screen shot for the footer issue, I can't see them on any page.

2022-03-20 13:13 UTC, Ariiiane commented
https://user-images.githubusercontent.com/53889883/159163958-a7e77426-c923-492b-b2c3-1a49ed6ba98a.mp4

Here is a video of what I see

2022-03-20 13:53 UTC, JR-prog requested changes
![image](https://user-images.githubusercontent.com/52092026/159165732-8cde35e8-4f59-49e1-bca5-bec32bd6c514.png)

Footer issue gone now, but the styling for the proceed button still seems off? I think its because I am checking it on my laptop (smaller screen), so you might have to make it more responsive.

2022-03-20 15:43 UTC, JR-prog requested changes
Button looks good. Added an extra comment about the footer that I missed in the last review.

2022-03-20 15:43 UTC, JR-prog commented on public/css/app.css
> +    position: absolute;
If this is absolute, then it doesn't work with smaller screen sizes (the footer will be in the middle of the content). 
![image](https://user-images.githubusercontent.com/52092026/159170409-eb55071d-703c-4f9c-ae5b-bc96844fe7e4.png)
(Sorry I didn't catch this problem on last review)
Either leave it as relative (which is uglier on bigger screens) or find another way to make it at the bottom only.

2022-03-21 01:19 UTC, JR-prog requested changes
The footer is still inconsistent in other pages. Worst case, can you just change it in the css for the cart page only?

2022-03-21 02:30 UTC, Ariiiane commented
Task: #20 - implementation of cart functionality
This task is now implemented
<img width="771" alt="image" src="https://user-images.githubusercontent.com/53889883/159198080-657637ac-18a3-4252-844d-c63318e56c3e.png">

2022-03-21 23:37 UTC, Ariiiane commented
Add to cart and delete functionalit

https://user-images.githubusercontent.com/53889883/159380201-b945f0fa-f1a4-4c6b-ba6d-9c125e9b90bc.mp4

y

2022-03-22 14:47 UTC, JR-prog requested changes
Adding and removing from cart works for me!

However, the last item in the cart is always hidden by the footer.

2022-03-22 16:51 UTC, Ariiiane commented
I fixed the footer by imposing a minimum height to the page

2022-03-22 17:35 UTC, JR-prog approved these changes
Works for me!

2022-03-22 17:38 UTC, merged